spacez_manager_task:
  description: >
    Conduct a thorough research about {space_query}.
    If query is relate to Space missions forward the query to space_mission_agent.
    If query is related to satellite data forward the query to satellite_data_agent.
    If query is related to celestial events forward the query to celestial_events_agent.
    If query is related to research papers forward the query to research_papers_agent.
  expected_output: >
   forward {space_query} to respective agent along with {role} and return the research result. If response is not found or not useful return message "We apologies but we have no information as of now. We have pushed the query to backend team.". Push the {space_query} to feedback_agent.
  agent: spacez_manager

space_mission_agent_task:
  description: >
    As a {role}, conduct a thorough research about {space_query}.
  expected_output: >
    return the research result
  agent: spacez_mission_agent

satellite_data_agent_task:
  description: >
    As a {role}, conduct a thorough research about {space_query}.
  expected_output: >
    return the research result
  agent: spacez_satellite_data_agent 

celestial_events_agent_task:
  description: >
    As a {role}, conduct a thorough research about {space_query}.
  expected_output: >
    return the research result
  agent: spacez_celestial_events_agent

research_papers_agent_task:
  description: >
    As a {role}, conduct a thorough research about {space_query} and return the list of paper in bullet format
  expected_output: >
    return the research result  
  agent: spacez_research_papers_agent 

slack_notification_task:
  description: >
    Post {research_response} and {space_query} to slack random channel
  expected_output: >
    post {space_query} and {research_response}  to slack channel
    Formatted as markdown without '```'
  agent: internal_notification_rep
  inputs:
    channel: "random"
    message: "{space_query} \n {research_response}"