spacez_manager_task:
  description: >
    Conduct thorough research on `{space_query}` and route it to the most relevant agent:
    - If the query relates to Space Missions, delegate to `space_mission_agent` **ONLY**.
    - If the query relates to Satellite Data, delegate to `satellite_data_agent` **ONLY**.
    - If the query relates to Celestial Events, delegate to `celestial_events_agent` **ONLY**.
    - If the query relates to Research Papers, delegate to `research_papers_agent` **ONLY**.
  
  expected_output: >
    - `{space_query}` is sent **only to one relevant agent** based on `{category}`.
    - The selected agent processes the request and returns the research result.
    - If in response noresult string is found, return:
      `"We apologize, but we have no information at this moment. Your query has been forwarded to the backend team for further research."`
    - The `{space_query}` is logged to `feedback_agent` for tracking.

  agent: spacez_manager
  allow_delegation: true  
  max_delegation_depth: 1  

space_mission_agent_task:
  description: >
    As a space mission specialist find out all details aboout space missions related to {space_query} for {role} and store in file names "resource_response.txt"
  expected_output: >
    - The selected agent processes the request and returns the research result.
    - If in response noresult string is found, return:
      We apologize, but we have no information at this moment. Your query has been forwarded to the backend team for further research.
  agent: spacez_mission_agent
  inputs:
    role: "{role}"
    query: "{space_query}"

satellite_data_agent_task:
  description: >
    As a {role}, conduct a thorough research about {space_query}.
  expected_output: >
    return the research result
  agent: spacez_satellite_data_agent 

celestial_events_agent_task:
  description: >
    As a {role}, conduct a thorough research about {space_query}.
  expected_output: >
    return the research result
  agent: spacez_celestial_events_agent

research_papers_agent_task:
  description: >
    As a information specialist for {role}, conduct a thorough research about {space_query} and return the list of items in bullet format and store in file names "resource_response.txt"
  expected_output: >
    return the research result in bullet format and return response to spacez_manager 
  agent: spacez_research_papers_agent 

slack_notification_task:
  description: >
    Post research response and {space_query} to slack random channel
  expected_output: >
    read from output_file "resource_response.txt" in {research_response} and post {space_query} and {research_response}  to slack channel
    Formatted as markdown without '```'
  agent: feedback_agent
  inputs:
    channel: "random"
    message: "{space_query} \n {research_response}"